[build-system]
requires = ["setuptools>=67.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["correction", "encoding", "parse", "validation"]

[project]
name = "simple_calculator"
version = "1.0.0"
dependencies = [
    "pandas",
]
