[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "simple_calculator"
version = "1.0.0"
description = "A simple calculator class with basic arithmetic operations"
authors = ["Your Name <your@email.com>"]
license = "MIT"
homepage = "https://github.com/your_username/simple_calculator"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
