[tool.poetry]
name = "simple_calculator"
version = "1.0.0"
description = "Your package description"
authors = ["Your Name <your@email.com>"]
license = "MIT"  # This line defines the license

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"


