name: Build Wheel

on:
  workflow_dispatch:

jobs:
  build-wheel:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # or your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt

    - name: Build wheel
      run: |
        mkdir -p wheelhouse
        pip wheel --wheel-dir=wheelhouse -r requirements.txt

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Action"
        git add wheelhouse/
        git commit -m "Add generated wheel files"
        git push https://github.com/mohitVec/test_install_package.git
